name: Dev Build and Push Docker Images

on:
  push:
  workflow_dispatch:
jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      service-a: ${{ steps.filter.outputs.service-a }}
      service-b: ${{ steps.filter.outputs.service-b }}
      service-c: ${{ steps.filter.outputs.service-c }}
      config: ${{ steps.filter.outputs.config }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes in directories
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            service-a:
              - 'service-a/**'
            service-b:
              - 'service-b/**'
            service-c:
              - 'service-c/**'
            config:
              - '.env'
              - 'config/**'
              - 'docker-compose'
      - name: Save change status for service-a
        if: ${{ steps.filter.outputs.service-a == 'true' }}
        run: echo "service-a=true" > service-a.txt
      - name: Save change status for service-b
        if: ${{ steps.filter.outputs.service-b == 'true' }}
        run: echo "service-b=true" > service-b.txt
      - name: Save change status for service-c
        if: ${{ steps.filter.outputs.service-c == 'true' }}
        run: echo "service-c=true" > service-c.txt
      - name: Upload artifacts
        if: always()  # This will upload regardless of changes
        uses: actions/upload-artifact@v3
        with:
          name: change-status
          path: |
            service-a.txt
            service-b.txt
            service-c.txt
          retention-days: 3
