---
name: Dev Deploy intercom sync worker
on:
  workflow_run:
    workflows: ["Dev Build and Push Docker Images"] 
    types:
      - completed
jobs:
  ec2-deployment:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Detect changes in directories
        id: filter
        uses: dorny/paths-filter@v3
        with:
          filters: |
            services:
              - 'service-*/**'

      - name: Deploy Application
        if: ${{ steps.filter.outputs.services == 'true' }}
        run: echo "Deploying application because Service A or Service B changed."